In [32]:
import csv
import ast

f = open('data.csv', 'r')
data = f.readlines()
reader = csv.reader(data)
data2 = []
ams = []
for r in reader:
    data2.append(r)
data3 = []
for line in data2:
    tmp = []
    for element in line:
        tmp.append([int(element[0]), int(element[1])])
    data3.append(tmp)

In [34]:
data3

[[[5, 8], [6, 7], [7, 5], [8, 3], [9, 4]],
 [[3, 0], [4, 9], [6, 7], [7, 8], [8, 2], [9, 1]],
 [[1, 4], [3, 0], [4, 8], [5, 7], [7, 2], [8, 3], [9, 5]],
 [[0, 5], [1, 0], [2, 3], [3, 2], [5, 4], [6, 8], [7, 6], [8, 7]],
 [[1, 0], [2, 4], [3, 5], [5, 6], [7, 9], [8, 2], [9, 8]],
 [[0, 9], [6, 1], [7, 6], [8, 7], [9, 8]],
 [[0, 5], [1, 6], [3, 8], [4, 7], [5, 4], [7, 9], [8, 2], [9, 3]],
 [[0, 5], [1, 9], [2, 7], [4, 6], [5, 8], [8, 3], [9, 1]],
 [[0, 8], [2, 9], [3, 5], [4, 1], [5, 2], [7, 4], [8, 3], [9, 7]],
 [[0, 8], [1, 6], [2, 5], [4, 7], [6, 4], [8, 9], [9, 0]],
 [[0, 9], [3, 2], [5, 4], [7, 5], [8, 7], [9, 8]],
 [[0, 4], [2, 0], [3, 5], [4, 8], [7, 9], [9, 3]],
 [[0, 3], [1, 8], [2, 9], [3, 7], [4, 6], [6, 1], [7, 2], [8, 4]],
 [[1, 3], [4, 6], [5, 7], [6, 5], [7, 9], [9, 4]],
 [[6, 7], [7, 8], [8, 5], [9, 6]],
 [[0, 6], [1, 8], [2, 7], [3, 9], [4, 5], [5, 4]],
 [[1, 5], [2, 4], [3, 1], [4, 3], [5, 6], [6, 2], [8, 9], [9, 8]],
 [[0, 7], [1, 5], [2, 4], [6, 8], [7, 9], [8, 6], [9,

In [35]:
import numpy as np

within_list = []
across_list = []
totals_list = []
for i, a in enumerate(data3):
    totals_list.append(len(a))
    within_list.append(0)
    across_list.append(0)
    for el in a:
        if not 8 in el and not 9 in el:
            if el == [0, 1] or el == [1, 0] or el == [2, 3] or el == [3, 2] or el == [4, 5] or el == [5, 4] or el == [6, 7] or el == [7, 6]:
                within_list[-1] += 1
            else:
                across_list[-1] += 1
within_list_proportion = [float(x)/float(y) if y is not 0 else np.nan for x, y in zip(within_list, totals_list)]
across_list_proportion = [float(x)/float(y) if y is not 0 else np.nan for x, y in zip(across_list, totals_list)]

In [36]:
with open('misassignments_by_context.csv', 'w') as fp:
    fp.write('total_misassignments,within_misassignments,across_misassignments,within_misassignment_proportions,across_misassignment_proportions\n')
    for t, w, a, wp, ap in zip(totals_list,within_list ,across_list,within_list_proportion,across_list_proportion):
        fp.write('{0},{1},{2},{3},{4}\n'.format(t, w, a, wp, ap))

In [4]:
sum(part_ams_within_context)

226

In [5]:
sum(part_ams_across_context)

300

In [6]:
within = [float(a)/float(n) if n != 0 else 0 for a, n in zip(part_ams_within_context, part_totals)]
across = [float(a)/float(n) if n != 0 else 0 for a, n in zip(part_ams_across_context, part_totals)]

In [7]:
import numpy as np
print(np.mean(part_ams_within_context))
print(np.std(part_ams_within_context))
print(np.std(part_ams_within_context)/np.sqrt(43))

5.25581395349
3.84643007703
0.586575087631


In [8]:
import numpy as np
print(np.mean(part_ams_across_context))
print(np.std(part_ams_across_context))
print(np.std(part_ams_across_context)/np.sqrt(43))

6.97674418605
4.54173602754
0.692608251028


In [9]:
import itertools
import numpy as np

p_of_within = 8.0/len([x for x in itertools.permutations(['a','b','c','d','e','f','g','h'], 2)])

print("p_within={0}".format(p_of_within))

print("mean={0}".format(np.mean(within)))
print("std={0}".format(np.std(within)))
print("ste={0}".format(np.std(within)/np.sqrt(43)))

p_within=0.142857142857
mean=0.428202035523
std=0.263518543821
ste=0.0401862011888


In [10]:
import itertools
import numpy as np

p_of_across = 1.0 - 8.0/len([x for x in itertools.permutations(['a','b','c','d','e','f','g','h'], 2)])

print("p_across={0}".format(p_of_across))

print("mean={0}".format(np.mean(across)))
print("std={0}".format(np.std(across)))
print("ste={0}".format(np.std(across)/np.sqrt(43)))

p_across=0.857142857143
mean=0.548542150524
std=0.268776171308
ste=0.0409879818639


In [11]:
part_totals = [0 for i in range(0, len(ams))]
part_ams_within_context = [0 for i in range(0, len(ams))]
part_ams_across_context = [0 for i in range(0, len(ams))]
for i, a in enumerate(ams):
    for el in a:
        if not 8 in el and not 9 in el:
            part_totals[i] += 1
            if el == [0, 1] or el == [1, 0] or el == [2, 3] or el == [3, 2] or el == [4, 5] or el == [5, 4] or el == [6, 7] or el == [7, 6]:
                part_ams_within_context[i] += 1
            else:
                part_ams_across_context[i] += 1

In [12]:
within = [float(a)/float(n) if n != 0 else np.nan for a, n in zip(part_ams_within_context, part_totals)]
across = [float(a)/float(n) if n != 0 else np.nan for a, n in zip(part_ams_across_context, part_totals)]

In [13]:
within_reshaped = np.reshape(within, (43, 4))
print("p_within={0}".format(p_of_within))

print("mean={0}".format(np.nanmean(within_reshaped, axis=0)))
print("std={0}".format(np.nanstd(within_reshaped, axis=0)))
print("ste={0}".format(np.nanstd(within_reshaped, axis=0)/np.sqrt(43)))

p_within=0.142857142857
mean=[ 0.25        0.41153846  0.65945946  0.64141414]
std=[ 0.27853073  0.37654059  0.35085782  0.37632194]
ste=[ 0.04247554  0.0574219   0.05350532  0.05738856]


In [14]:
across_reshaped = np.reshape(across, (43, 4))
print("p_across={0}".format(p_of_across))

print("mean={0}".format(np.nanmean(across_reshaped, axis=0)))
print("std={0}".format(np.nanstd(across_reshaped, axis=0)))
print("ste={0}".format(np.nanstd(across_reshaped, axis=0)/np.sqrt(43)))

p_across=0.857142857143
mean=[ 0.75        0.58846154  0.34054054  0.35858586]
std=[ 0.27853073  0.37654059  0.35085782  0.37632194]
ste=[ 0.04247554  0.0574219   0.05350532  0.05738856]


In [15]:
print([x+y for x, y in zip(within, across)])
print(np.nanmean(within_reshaped, axis=0) + np.nanmean(across_reshaped, axis=0))

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, nan, nan, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, nan, nan, 1.0, 1.0, 1.0, 1.0, nan, nan, nan, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, nan, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[ 1.  1.  1.  1.]


In [18]:
within_reshaped

array([[ 0.5       ,  0.        ,  0.        ,  0.25      ],
       [ 0.5       ,  0.        ,  1.        ,         nan],
       [ 0.        ,  0.2       ,  0.8       ,  0.        ],
       [ 0.83333333,  1.        ,  1.        ,  1.        ],
       [ 0.25      ,  0.        ,  0.25      ,  0.25      ],
       [ 0.5       ,         nan,         nan,  1.        ],
       [ 0.25      ,  0.5       ,  1.        ,  1.        ],
       [ 0.        ,  0.83333333,  0.33333333,         nan],
       [ 0.        ,  0.        ,  0.25      ,  0.25      ],
       [ 0.        ,  0.25      ,  0.33333333,  0.        ],
       [ 0.66666667,  1.        ,  1.        ,         nan],
       [ 0.        ,  0.33333333,  0.33333333,         nan],
       [ 0.        ,  0.2       ,  1.        ,  0.5       ],
       [ 0.        ,  0.4       ,  0.33333333,  0.75      ],
       [ 1.        ,  0.4       ,  0.5       ,         nan],
       [ 0.5       ,  0.25      ,  0.2       ,  0.66666667],
       [ 0.        ,  0.

In [19]:
across_reshaped

array([[ 0.5       ,  1.        ,  1.        ,  0.75      ],
       [ 0.5       ,  1.        ,  0.        ,         nan],
       [ 1.        ,  0.8       ,  0.2       ,  1.        ],
       [ 0.16666667,  0.        ,  0.        ,  0.        ],
       [ 0.75      ,  1.        ,  0.75      ,  0.75      ],
       [ 0.5       ,         nan,         nan,  0.        ],
       [ 0.75      ,  0.5       ,  0.        ,  0.        ],
       [ 1.        ,  0.16666667,  0.66666667,         nan],
       [ 1.        ,  1.        ,  0.75      ,  0.75      ],
       [ 1.        ,  0.75      ,  0.66666667,  1.        ],
       [ 0.33333333,  0.        ,  0.        ,         nan],
       [ 1.        ,  0.66666667,  0.66666667,         nan],
       [ 1.        ,  0.8       ,  0.        ,  0.5       ],
       [ 1.        ,  0.6       ,  0.66666667,  0.25      ],
       [ 0.        ,  0.6       ,  0.5       ,         nan],
       [ 0.5       ,  0.75      ,  0.8       ,  0.33333333],
       [ 1.        ,  1.

In [26]:
[int(x) for i, x in enumerate(np.transpose(data2)[0]) if i%4==0]

[21,
 22,
 23,
 24,
 25,
 26,
 27,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 45,
 46,
 48,
 49,
 50,
 51,
 52,
 55,
 56,
 57,
 58,
 59,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 69,
 71,
 72,
 73,
 74]